version: '3.8'

services:
    backend:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        environment:
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWORD=rootpassword
            - DB_NAME=k8s_lb_logs
        depends_on:
            - mysql
        networks:
            - app-network

    frontend:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - '8080:80'
        environment:
            - BACKEND_URL=http://localhost:5000
        depends_on:
            - backend
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: k8s_lb_logs
        ports:
            - '3306:3306'
        volumes:
            - ./mysql_migrations:/docker-entrypoint-initdb.d
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
