apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
# The values need to be in base64
data:
  # ZJRP*SLkw37JST*i2M
  mysql-password: WkpSUCpTTGt3MzdKU1QqaTJN
  # MTk8s_lb_logs
  mysql-database: TVRrOHNfbGJfbG9ncw==
